package view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author clebe
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMnCadUsuario = new javax.swing.JMenuItem();
        jMnCadCliente = new javax.swing.JMenuItem();
        jMnCadFornecedor = new javax.swing.JMenuItem();
        jMnCadProduto = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Principal");

        jMenu1.setText("Arquivo");

        jMnCadUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMnCadUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMnCadUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usario.png"))); // NOI18N
        jMnCadUsuario.setText("Cadastro de Usuário");
        jMnCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnCadUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMnCadUsuario);

        jMnCadCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMnCadCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMnCadCliente.setText("Cadastro de Cliente");
        jMnCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnCadClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMnCadCliente);

        jMnCadFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMnCadFornecedor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMnCadFornecedor.setText("Cadastro de Fornecedores");
        jMnCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnCadFornecedorActionPerformed(evt);
            }
        });
        jMenu1.add(jMnCadFornecedor);

        jMnCadProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMnCadProduto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMnCadProduto.setText("Cadastro de Produtos");
        jMnCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnCadProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(jMnCadProduto);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sobre");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMnCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnCadUsuarioActionPerformed
        TelaCadastroUsuario tela = new TelaCadastroUsuario();
        tela.setVisible(true);
    }//GEN-LAST:event_jMnCadUsuarioActionPerformed

    private void jMnCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnCadFornecedorActionPerformed
        TelaCadastroFornecedor tela = new TelaCadastroFornecedor();
        tela.setVisible(true);
    }//GEN-LAST:event_jMnCadFornecedorActionPerformed

    private void jMnCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnCadProdutoActionPerformed
        TelaCadastroProduto tela = new TelaCadastroProduto();
        tela.setVisible(true);
    }//GEN-LAST:event_jMnCadProdutoActionPerformed

    private void jMnCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnCadClienteActionPerformed
        TelaCliente tela = new TelaCliente();
        tela.setVisible(true);
    }//GEN-LAST:event_jMnCadClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JMenuItem jMnCadCliente;
    public static javax.swing.JMenuItem jMnCadFornecedor;
    public static javax.swing.JMenuItem jMnCadProduto;
    public static javax.swing.JMenuItem jMnCadUsuario;
    // End of variables declaration//GEN-END:variables
}
