/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import util.Senha;
import view.TelaCadastroUsuario;

/**
 *
 * @author Geral
 */
public class TelaGerarSenha extends javax.swing.JFrame {

    /**
     * Creates new form TelaGerarSenha
     */
    public TelaGerarSenha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLblOpcoes = new javax.swing.JLabel();
        jBttnGerar = new javax.swing.JButton();
        jTxtFldSenhaGerada = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jRdBttnCaractereSpeciais = new javax.swing.JRadioButton();
        jRdBttnNumeros = new javax.swing.JRadioButton();
        jRdBttnMinuscula = new javax.swing.JRadioButton();
        jRdBttnMaiuscula = new javax.swing.JRadioButton();
        jRdBttnTodos = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerar Senha");

        jLblOpcoes.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLblOpcoes.setText("Opções:");

        jBttnGerar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBttnGerar.setText("Gerar");
        jBttnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnGerarActionPerformed(evt);
            }
        });

        jTxtFldSenhaGerada.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel1.setText("Senha Gerada:");

        buttonGroup1.add(jRdBttnCaractereSpeciais);
        jRdBttnCaractereSpeciais.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRdBttnCaractereSpeciais.setText("Caracteres Especiais");

        buttonGroup1.add(jRdBttnNumeros);
        jRdBttnNumeros.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRdBttnNumeros.setText("Números");

        buttonGroup1.add(jRdBttnMinuscula);
        jRdBttnMinuscula.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRdBttnMinuscula.setText("Minúsculas");

        buttonGroup1.add(jRdBttnMaiuscula);
        jRdBttnMaiuscula.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRdBttnMaiuscula.setText("Maiúsculas");

        buttonGroup1.add(jRdBttnTodos);
        jRdBttnTodos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRdBttnTodos.setText("Todos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jBttnGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLblOpcoes)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRdBttnNumeros)
                            .addComponent(jRdBttnMinuscula)
                            .addComponent(jRdBttnMaiuscula)
                            .addComponent(jRdBttnCaractereSpeciais)
                            .addComponent(jRdBttnTodos)
                            .addComponent(jTxtFldSenhaGerada, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblOpcoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jRdBttnMaiuscula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRdBttnMinuscula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRdBttnNumeros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRdBttnCaractereSpeciais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRdBttnTodos)
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtFldSenhaGerada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBttnGerar)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBttnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnGerarActionPerformed
    if(jRdBttnMaiuscula.isSelected()){
    jTxtFldSenhaGerada.setText(Senha.gerarMaiusculo());
    TelaCadastroUsuario.jTxtSenha.setText(jTxtFldSenhaGerada.getText());
    }
    if(jRdBttnMinuscula.isSelected()){
    jTxtFldSenhaGerada.setText(Senha.gerarMinusculo());
    TelaCadastroUsuario.jTxtSenha.setText(jTxtFldSenhaGerada.getText());
    }
    if(jRdBttnNumeros.isSelected()){
    jTxtFldSenhaGerada.setText(Senha.gerarNumero());
    TelaCadastroUsuario.jTxtSenha.setText(jTxtFldSenhaGerada.getText());
    }
    if(jRdBttnCaractereSpeciais.isSelected()){
    jTxtFldSenhaGerada.setText(Senha.gerarCaracteres());
    TelaCadastroUsuario.jTxtSenha.setText(jTxtFldSenhaGerada.getText());
    }
    if(jRdBttnTodos.isSelected()){
    jTxtFldSenhaGerada.setText(Senha.gerarSenhaTodos());
    TelaCadastroUsuario.jTxtSenha.setText(jTxtFldSenhaGerada.getText());
    }
    }//GEN-LAST:event_jBttnGerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGerarSenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBttnGerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblOpcoes;
    private javax.swing.JRadioButton jRdBttnCaractereSpeciais;
    private javax.swing.JRadioButton jRdBttnMaiuscula;
    private javax.swing.JRadioButton jRdBttnMinuscula;
    private javax.swing.JRadioButton jRdBttnNumeros;
    private javax.swing.JRadioButton jRdBttnTodos;
    private javax.swing.JTextField jTxtFldSenhaGerada;
    // End of variables declaration//GEN-END:variables
}
